### ISSUE TITLE
Google OAuth hanging

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#132]

**Comment by dimasciput** [comment]
@gubuntu are you testing this on testing.limpopo? Because I didn't register that site to google and github oauth.

**Comment by gubuntu** [comment]
no I'm doing all testing on staging

**Comment by dimasciput** [comment]
@gubuntu I tested on the staging site and it was working fine for me. @ann26 can you also test this?

**Comment by ann26** [comment]
hi @gubuntu and @dimasciput 
I tested the https://staging.limpopobims.kartoza.com/ and I can login both using my google account and github account.

**Comment by gubuntu** [comment]
Just tried again and it now proceeds but this page needs styling:

<img width="808" alt="screen shot 2018-07-05 at 08 08 01" src="https://user-images.githubusercontent.com/496911/42305332-cdb9e06c-802a-11e8-9a85-301a406c067e.png">

and how would one do this?

`An account already exists with this e-mail address. Please sign in to that account first, then connect your Google account.`

**Comment by ann26** [comment]
hi @gubuntu it is because you sign in with different social account that have the same email address with your existing account in database.

For example: one day you have signed in with a google account which uses email address example@kartoza.com, then 2 days later you try to sign in with a github account with the same email address (example@kartoza.com). The system won't allow you to have two account with the same email address. Please try to sign in with another email address?

**Comment by gubuntu** [comment]
valid explanation
