### ISSUE TITLE
Validation on upload 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/LEDET_BIMS#146]
## Problem 

Once your upload is successful, you will be able to edit it while it awaits validation. Once it is validated, you will no longer be able to edit it.

@carina1000 can you create a mockup for this, we need to able show thousands of data so pagination is needed. 

child of #24

**Comment by gubuntu** [comment]
or you could give role-specific admin access like @lucernae did in InaSAFE Realtime? (rather than creating a custom user view)

then again this is a workflow / business process so we should be thinking bigger picture and establishing proper bpm (business process management) in our Django apps (there are probably some apps to facilitate bpm)

(btw this is covered in #21 #23 #24)
