### ISSUE TITLE
backup and restore lbims geonode into new geonode orchestration

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#158]
BIMS + GeoNode are now integrated and deployed on testing. 

All the content (which is production-ready) that is on lbimsgis.kartoza.com must be backed up and restored to testing

lbimsgis will remain the canonical copy until eventualy deployed to LEDET production servers in a formal release.

child of #4

**Comment by NyakudyaA** [comment]
@dimasciput from the orchestration you have set-up we need the following:
* 2 instances of the database so that we can have the Django and spatial database as separate. The spatial database will be linked to GeoServer and we upload layers using Django management layers. We should also configure Geonode to use this spatial database as the backend for people who upload using the GUI (although our Geonode should not be primarily used for this)
* We need to add btsync for managing backups.

NB: Can we schedule a time tomorrow @10 am SA time where we can go through restoring the backup Geonode and see how it goes.

**Comment by NyakudyaA** [comment]
@gubuntu  Geonode principle from 2.8.0 is to separate the databases. Whilst it is ok to utilize the same database I guess it's just tidy and prevents people with unauthorized access to play around with the Django tables. 
* The biggest drawback is just mixing Django tables with spatial data.

**Comment by NyakudyaA** [comment]
Geonode DB has been added as an additional database cluster.

**Comment by NyakudyaA** [comment]
@gubuntu  the GeoServer DB is a separate database cluster. 

![geonode-db](https://user-images.githubusercontent.com/2510900/43700660-bdffb876-9953-11e8-92d1-2fdefb857069.png)

Geonode DB is in the same Django DB as BIMS.
![db1](https://user-images.githubusercontent.com/2510900/43700855-73fed6a2-9954-11e8-8c1e-5a0b1b9503d6.png)

**Comment by NyakudyaA** [comment]
I have updated the metadata which still had lbims links

**Comment by gubuntu** [comment]
@NyakudyaA please close if you've tested and are happy

**Comment by NyakudyaA** [comment]
All layers are working properly
