### ISSUE TITLE
FR40 implement approval workflow for GIS layers in BIMS admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#43]
Once the process in #42 is complete, another round of approval is necessary in the BIMS admin to add GIS layers to the BIMS app and assign them to BIMS user roles.

using Django WMS would facilitate this

depends on #42
requires #63

child of #29

**Comment by timlinux** [comment]
@ismailsunni we need a property in the WMS app that defines which users (or groups of users) may add/access each WMS layer. The OL widget would then only show eligible​ layers for adding as overlays to the map based on the user's permissions.

**Comment by ismailsunni** [comment]
The last discussion, we will not use django-wms and use geonode for this feature. Should I close it?

**Comment by gubuntu** [comment]
@meomancer merged this to configure layers in the BIMS map: https://github.com/kartoza/django-bims/pull/141

@ismailsunni could you test that layers assigned to a GeoNode group (BIMS role) appear in the BIMS map when a user belonging to that group is logged in and conversely that layers not assigned to that group (and not public) are not visible to that user. 

We can't close this until the use case has been satisfied

**Comment by timlinux** [comment]
@ismailsunni I discussed this with @gubuntu last week and he has a much simpler approach that I think we should use. For recap our original idea was to tag specific layers in GeoNode which we want to make available in the map:

![screen shot 2018-07-30 at 10 26 46](https://user-images.githubusercontent.com/178003/43386172-22331872-93e3-11e8-8518-b73e24b66fc0.png)


Gavin's proposal is much simpler:

Since we share now GeoNode and BIMS in a single platform we can have a scheme where:

* public layers will be available to all users
* logged in users will be able to add any layer they have permissions for in GeoNode

So I propose that you add a simple widget to the map like this:

![screen shot 2018-07-30 at 10 32 02](https://user-images.githubusercontent.com/178003/43386436-e3b94228-93e3-11e8-851f-87fa8242bde1.png)

Populate the widget from the geonode layers model, filtered by user's permissions.

**Comment by timlinux** [comment]
When you type something in the filter widget the list should be reduced to match the filter.

**Comment by gubuntu** [comment]
@timlinux @ismailsunni I don't want an 'add layer' widget, it is unnecessary work in our tight timeline and an unnecessary for the user to add layers. The map layer selector that is already there must just be automatically populated with all the layers the user has permission to see.

It is already populate with all layers, the permission filter just needs to be applied.

**Comment by timlinux** [comment]
@gubuntu agreed that we should merge this into the Map Layer Selector widget (sorry I hadnt seen that widget before).

I would like @ismailsunni to make a hybrid of his widget and the current Map Layer Selector widget so that we can filter layers (to deal with use case where there are 100's of layers). The current Map Layer Selector UI is nice so we would keep that sortable checklist implementation and add and remove layers to that list when the filter widget is used.

**Comment by gubuntu** [comment]
@ismailsunni this ticket is just about permissions. Please move discussion of the layer selector UI to #29 and take over from or help @sonlinux
