### ISSUE TITLE
FR41 PostGIS and folder permissions

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#44]
GIS users have read access to GIS folders and schemas

GIS admins have write access to GIS folders and schemas

**Comment by NyakudyaA** [comment]
@gubuntu I think we can implement the roles in the database:
```
CREATE ROLE editor
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE admin
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

--create a schema to use
CREATE SCHEMA data;

GRANT USAGE ON SCHEMA data to editor;

GRANT USAGE ON SCHEMA data to admin;

GRANT SELECT ON ALL TABLES IN  SCHEMA data to editor;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN  SCHEMA data to admin;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA data to editor;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA data to admin;

--create login roles for users
CREATE ROLE sample LOGIN ENCRYPTED PASSWORD 'password'
   VALID UNTIL 'infinity';

GRANT editor TO sample;
```
For folder RW or RO access, we need to set up that on the server using samba 

This issue is related to #41

**Comment by gubuntu** [comment]
please document in the permission matrix google sheet before implementing

Then the implementation needs to be scripted and committed to the repo

**Comment by timlinux** [comment]
See https://github.com/dperson/samba

**Comment by NyakudyaA** [comment]
Have separated this issue because this has been implemented and working.

Example 
We have a user called pam.
pam belong to the protected_area admin group. This group can either be RO or RW.

where they are explicitly
pam_editor: **RO** permissions for all layers
pam_admin: **RW** permissions for all layers

Pam can only see the layers that have been assigned permissions to her.

![screenshot 2018-11-29 at 15 32 18](https://user-images.githubusercontent.com/2510900/49225158-00706f00-f3ec-11e8-91ba-f134b491a225.png)

Tested locally with a pg_dump from production and all permissions being the same.

 #306
