### ISSUE TITLE
NFR9 provide API

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#57]
> The LBIMS should make data easily accessible to partner systems by providing a discoverable and easy to consume API

1. The only partner system in scope is SANBI. @cchristelis what are their requirements? see #59
1. Internally we also need a GeoJSON REST API for GIS services and users to pull biodiv records from the BIMS (role-based)

**Comment by timlinux** [comment]
In the API we should provide a way to get Darwin Core documents out. We could also look at GBIF node requirements as there might be libraries that will 'do it all' for us:

See also https://www.gbif.org/document/80925/establishing-an-effective-gbif-participant-node - if we can set things up so that we are a GBIF node that might be an effective way to go about it.

**Comment by gubuntu** [comment]
closing as duplicate of #59
