### ISSUE TITLE
Lock down Geoserver and integrate BIMS and GeoNode auth

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#61]
Ideally no public access should be allowed directly to Geoserver. All access should be proxied through GeoNode and controlled by BIMS OAuth user permissions.

child of #4

**Comment by NyakudyaA** [comment]
Added service rules in Geoserver to allow authenticated users direct access to standalone Geoserver.  When Geonode auth works it will also allow users to see layers that they have permissions against

**Comment by gubuntu** [comment]
Geoserver rules should block everyone except admin, or we just block the geoserver url from outside access with nginx, so everyone has to access it via GeoNode.

**Comment by NyakudyaA** [comment]
with the user model and permissions in Geonode only admin users have access to the Geoserver link menu.  There are no users defined in Geoserver and the default password specified in the docker-compose should be changed to a strong password once we logged into geoserver as admin.

**Comment by NyakudyaA** [comment]
![users.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46fd879f3191c1e5cdf9ad4cae58f3806b1c65262805a77a21d3e17ee94678545e5f4ead135d0b17f8fa8c39baa47e21d40854b088270a36d43703adbf881eba02be238f4c82b4b98b44c7fa70.png)
If a user manages to go to the geoserver URL and logs in using the  Geonode button he only sees this preview

**Comment by NyakudyaA** [comment]
Geofence permisions are fine grained. A user is only allowed to see layers he has been allocated permisions for in Geonode.

Example this anonymous user can only see the public layers
![screen shot 2018-09-17 at 15 29 14](https://user-images.githubusercontent.com/2510900/45625979-7f613700-ba8e-11e8-855d-8769c99f251f.png)

And in geoserver even if he logs in he also can only see the preview of the layers he has permissions against.

@gubuntu I think we should close this because this is the expected behaviour from Geonode. 

The main issue is to update permissions accordingly for each layer

**Comment by gubuntu** [comment]
agreed
